export const TAKE_SNAPSHOT = 'TAKE_SNAPSHOT';
export const RECEIVE_SNAPSHOT = 'RECEIVE_SNAPSHOT';
export const SET_BASELINE = 'SET_BASELINE';
export const RECEIVE_BASELINE = 'RECEIVE_BASELINE';
export const DO_DIFF = 'DO_DIFF';